### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/WUT#7]
Can you look at the database and see if bryankane and I are connections?

**Comment by jcaruso001** [comment]
I'm going to use this to track the issue I'm having with connections

**Comment by c-butcher** [comment]
Yeah, here is your user information. You're ID 42 and Bryan is ID 45
![image](https://cloud.githubusercontent.com/assets/1325362/7092889/de039130-df69-11e4-83f8-23f62e17e9e1.png)

You can see the connection here
![image](https://cloud.githubusercontent.com/assets/1325362/7092929/223ddfd6-df6a-11e4-8733-48b3f71730d3.png)

**Comment by jcaruso001** [comment]
When I make the call pull_friend_feeds I get this:

Get new Connections feeds: {"time":"2015-01-01 00:00:00"}
JSON response to Get Connections Feed: {"success":true,"data":[]}

and it looks like he has a post....

**Comment by c-butcher** [comment]
Hopefully [adding bi-directional relationships](https://github.com/Project-Caruso/Whats-Up-Tonight/commit/8a23e2a6703740f7825b2e1279ee13019876bd49) will fix the problem.

The problem was that it only created the relationship for the user who posted the friends list (Bryan). So I changed it so it creates 2 relationships (one for the person who posted, and one for the person who did not).

I'm going to delete your current relationships ... and it will require you to post your friend list again.

**Comment by jcaruso001** [comment]
Verified
